# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20161101_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horns',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horns', to=settings.AUTH_USER_MODEL),
        ),
    ]
