# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0003_auto_20161101_0816'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horns',
            unique_together=set([('album', 'author')]),
        ),
    ]
