# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20161101_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='tracks')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track', to='albums.Album')),
            ],
        ),
    ]
